[package]
name = "aburmd"
version = "1.0.0"
description = "AburMD - Minimalist Markdown Reader and Editor by AburMD Software"
authors = ["AburMD Software"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-dialog = "2.0.0"
tauri-plugin-fs = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
